### ISSUE TITLE
Base map and VPS setup

### ISSUE THREAD

**Issue by kykuyo** [kykuyo/ky-ardk-jam#2]
- Set up the base map
- Set up reading the VPS locations
- Placing location icons on the map
- Making these locations tappable so we can enter:
- The scene we enter is empty (maybe an empty ar experience), but has a close/x button.

**Comment by daftlive** [comment]
Implemented basic map functionality with VPS location markers and interaction.

https://github.com/kykuyo/ky-ardk-jam/assets/20849341/8b4294e8-f008-433b-99e6-defec593f5c6

**Comment by kykuyo** [comment]
Will create PR for Patrick to test build locally
