### ISSUE TITLE
Pull together art assets including models

### ISSUE THREAD

**Issue by kykuyo** [kykuyo/ky-ardk-jam#9]
Need the follow art assets:

- [x] Confirm we want to proceed with the 2D assets https://assetstore.unity.com/packages/2d/gui/icons/2d-casual-ui-hd-82080
- [x] Pet model + animations:
  - Walk forward
  - Sidestep
  - Turn left / right
  - Eat berry
  - Head shake (due to already having max energy)
  - Spraying water in AR
  - Success in AR
  - Out of energy in AR
  - Basic idle
- [x] ~~Berries (3D or 2D), or energy icons~~ -> keep it an energy icon, that same icon matching in the bar, use the invert normal backface culling fake outline.
- [x] Maybe: Gloo globe + animation -> thinking we'll do two crossing circle wires around the inner part; for exploding or defusing, can make use of some particles + basic animation of the shell itself. Aim for simpler materials (in case we want to modify them)
- [ ] Need a button for spew vs clean mode
- [x] 3D icon, whole icon is the top color -> just a generic 3D pointer icon like google maps.
- [x] Tripalaner shading for the ground -> mock it out
  - Roads+highways, 
- [x] Avatar: generic skeleton: just walk forward, running, sprint (if the player is in a car...), idle.

And mockup UI designs for:
- [x] Overlay "You are not looking at the anchor"
- [x] Map overlay and colors proposal
- [x] Success, "Congrats! you Won! Back to map / close button
- [x] Instructions to handoff between

**Comment by TheDuckCow** [comment]
## For the main player character:

- We could just use our pre-existing avatar, I don't see much harm in that. Bonus would be changing the accent color to match the current team assignment. In the interest of time, might not be a bad solution
- Or we could use one [from here](https://kenney.nl/assets/animated-characters-2) - though it says animations included, I inspected and think we'd need to redo them anyways.
  - ![Image](https://github.com/kykuyo/ky-ardk-jam/assets/2958461/9741d50a-cd4f-4d94-892c-6fbfe4c1dcc2)
  - This lends itself to the simpler flatter textures we could use elsewhere perhaps. We could change the shirt design to be a "splat"
- Or could go much more abstract and just do a solid color body with cell shading, such as [those here](https://assetstore.unity.com/packages/3d/characters/humanoids/ultimate-hypercasual-characters-43-bodytypes-202182) (if we go in this direction, I can find or make this myself, and probably find some good animations too) 
- These sytlized more like [lowpoly anime](https://assetstore.unity.com/packages/3d/characters/customizable-anime-character-3d-239978)
- Or this [stylized humanoid](https://assetstore.unity.com/packages/3d/characters/be-kind-sim-149381)
- Whatever we pick, should pair with the buddy choice below


## For the buddy:

Ones I like:

- [Liking this option](https://www.unrealengine.com/marketplace/en-US/product/cute-creature) as being very abstract. Could color saturation skin based on energy or something like that.
- Cute [dino character](https://www.unrealengine.com/marketplace/en-US/product/dino)
- [Kawaii slimes](https://assetstore.unity.com/packages/3d/characters/creatures/kawaii-slimes-221172) are also adorable and nicely abstract, and already prepared for Unity

Ones I don't like as much:

- [From this pack](https://assetstore.unity.com/packages/3d/characters/animals/quirky-series-free-animals-pack-178235), could pick e.g. the snake or salamander from here, both could be edited to open and 'spew'
- Could go with a pig-character (not [necessarily this one specifically](https://assetstore.unity.com/packages/3d/characters/animals/mammals/farm-pig-cute-series-260401), but could be a direction to go in)
- Could go more in the direction of something like an abstract worm (pushed more in the direction of a kirby-like character)
- Could do an antthro pet friend like [this one](https://www.unrealengine.com/marketplace/en-US/product/brave-cat)
